### ISSUE TITLE
Tooling in Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by wangkanai** [weidazhao/Hosting#16]
Hi! David,

I was trying load your solution in visual studio 2015 update 2 to evaluate how everything work.
seem that projects are not loading at all.
![image](https://cloud.githubusercontent.com/assets/10666633/15098583/9306613e-156a-11e6-8702-ed727a9e00de.png)
When i try load them and i get this message.
![image](https://cloud.githubusercontent.com/assets/10666633/15098532/11b0c66a-156a-11e6-8c20-e8c2c2ff8431.png)
I checked and have i have install the lastest [dotnet rc2 cli ](https://github.com/dotnet/cli)
![image](https://cloud.githubusercontent.com/assets/10666633/15098615/316cb706-156b-11e6-983f-a181b56d56ef.png)
Is there something else i need, to get your project up and running?

Thank you mate

Sarin

**Comment by MartinJohns** [comment]
Hey @wangkanai,

This might be related to this issue:
aspnet/Announcements#176 - ASP.NET Core RC2 is no longer compatible with DNX

Best is to wait a while until they released an updated tooling for RC2 support. The release of RC2 is scheduled for mid may.

**Comment by weidazhao** [comment]
@wangkanai , VS tooling for ASP.NET Core RC2 is not released yet. Please follow https://github.com/weidazhao/Hosting#how-to-build--run-the-sample to build and run the sample from command line for now. As @MartinJohns said, the schedule of RC 2 release has been announced, stay tuned..
