### ISSUE TITLE
problem with command line deploy

### ISSUE THREAD

**Issue by steve-torchia** [weidazhao/Hosting#18]
Hi,

I'm having a problem trying to run the Connect-ServiceFabricCluster command.   I've never run into this when doing the deploy/run from inside Visual Studio.  Is there something obvious I'm missing?

thanks

-steve

> Connect-ServiceFabricCluster localhost:19000 | .\Scripts\Deploy-FabricApplication.ps1 -PublishProfileFile .\PublishPro
> files\Local.xml -ApplicationPackagePath .\pkg\Debug\ -OverwriteBehavior Always

WARNING: Failed to contact Naming Service. Attempting to contact Failover Manager Service...
WARNING: Failed to contact Failover Manager Service, Attempting to contact FMM...
WARNING: No connection could be made because the target machine actively refused it 127.0.0.1:19000
Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS
issue.
At line:1 char:1
- Connect-ServiceFabricCluster localhost:19000 | .\Scripts\Deploy-Fabri ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricException
  - FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster

**Comment by weidazhao** [comment]
Can you check if the cluster is running?

**Comment by steve-torchia** [comment]
Ok I got past that first error.  The cluster was running but the powershell window was not running as administrator.

Now I'm getting a little farther but the package is not passing Test-ServiceFabricApplicationPackage:

Connect-ServiceFabricCluster localhost:19000 | .\Scripts\Deploy-FabricApplication.ps1 -PublishProfileFile .\PublishProfiles\Local.xml -ApplicationPackagePath .\pkg\Debug\ -OverwriteBehavior Always

> WARNING: Cluster connection with the same name already existed, the old connection will be deleted
> WARNING: Cluster connection with the same name already existed, the old connection will be deleted
> Test-ServiceFabricApplicationPackage : The EntryPoint Counter.exe is not found.
> FileName:
> C:\Users\dev\AppData\Local\Temp\TestApplicationPackage_11399809123\m5ky42qo.5lt\Debug\Counter\ServiceManifest.xml
> At C:\Program Files\Microsoft SDKs\Service
> Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:108 char:34
> - ... tionSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse)
> -                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidati
>     onException
>   - FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage

**Comment by weidazhao** [comment]
What version of DotNet CLI did you install? You will need to have 1.0.0-preview1-002700.

**Comment by steve-torchia** [comment]
Ah, I did have the version you provided...alongside a handful of older versions.  After I removed(uninstalled) the older versions, it all works properly now.  Thanks and sorry for the noise

-steve
