### ISSUE TITLE
Runtime problem

### ISSUE THREAD

**Issue by antogh** [weidazhao/Hosting#2]
Hello Weida,
I downloaded the project and followed the instructions, it builds without problems however when I start debugging (F5) I have these runtime errors:
  C:\Users\sixgv.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16357\bin\dnu.cmd publish "C:\testsrc\Hosting-master\Web" --out "C:\Users\sixgv\AppData\Local\Temp\PublishTemp\Web39" --configuration Debug --runtime dnx-clr-win-x64.1.0.0-rc2-16357 --wwwroot "wwwroot" --wwwroot-out "wwwroot"

  Microsoft .NET Development Utility Clr-x86-1.0.0-rc2-16357
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(152,5): error : Unable to locate runtime 'dnx-clr-win-x64.1.0.0-rc2-16357'
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(152,5): error : Locations probed:
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(152,5): error : dnx-clr-win-x64.1.0.0-rc2-16357
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(152,5): error : C:\Users\sixgv.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc2-16357

Can you help me to solve this problem?

Beside that I gave a look to the sources and I quite understood the demo. There is only one service (a counter) that exposes directly the webapi enpoint to manipulate the counter thanks to this new AspNetCommunicationListener. That is a semplification over the model I saw in previous demo where to achieve the same 2 services were created: the counter was using ServiceRemotingListener to accept requests and the WebApi was a separate service communicating with the counter via ServiceProxy.

I'd like to run the new project to make some tests, any help appreciated, thanks.

**Comment by weidazhao** [comment]
Can you check if the x64 runtime is downloaded under %userprofile%.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc2-16357? If not, you need to run 'dnvm install 1.0.0-rc2-16357 -a x64 -u' from command line to grab it.

Check out the 'How to Build & Run The Sample' section in the readme.md.

**Comment by antogh** [comment]
I solved the problem.
Actually, the command:
'dnvm install 1.0.0-rc2-16357 -a x64 -u' 
does not work properly, it's just installing the x86 version over and over again.
It seems that that the -a command stand just for the alias so it's interpreting the following "x64" string as an alias for the x86 runtime not as the platform runtime type to download.
Tinkering with parameters I got the right way to install the x64 runtime with this command line:
'dnvm install 1.0.0-rc2-16357 -arch x64 -u'
You can eventually report the problem to dnvm authors and/or edit the demo install instructions.
Now the project run without problem with start debugging F5 and I can test successfully the REST api GET method from the browser. I need to install some tool to test also the POST method (was thinking about postman chrome extension).
Overall I like the new model shown by this project, one single reliable service is now able to expose directly a web api endpoint without the need of an additional service as was happening in previous demos shown in SF tutorials. 
For your convenience I have attached a log file with my attempts to get the right command line syntax to install the x64 runtime. Thank you for your help and best regards
[dnvm_attempts.txt](https://github.com/weidazhao/Hosting/files/84101/dnvm_attempts.txt)

**Comment by weidazhao** [comment]
Thanks antogh for the feedback. It appears to be a breaking change in DNVM. I was using DNVM 1.0.0-rc1.

To clarify, the prototype is just to demonstrate a better way of hosting ASP.NET 5 app in Service Fabric. It doesn't simplify the app architecture so that you would be able to just need one reliable stateful service and send request from client to it directly. 

The problem is that a stateful service could have multiple partitions and Service Fabric could move the replicas around within a cluster. So someone would need to figure out where to send requests, either the client itself or something in the middle between client and service. A typical pattern is to have a stateless service as a reverse proxy in front of the reliable stateful service in order to do mainly two things:
1. Calculate partition key based on the incoming request and use the key to resolve partition.
2. Redirect the request to the resolved partition.

I added a Gateway (reverse proxy) service in this repo to demonstrate the pattern. Note that it is just a prototype for demo purpose now.

**Comment by antogh** [comment]
Hello Weida, thanks for the clarification, makes perfect sense, my fault that I forgot about this detail. If I remember correctly in the real cluster (not the local dev machine simulation) the stateless service is usually on every node (instance_count = -1) behind a load balancer so you can have a unique fixed address exposed to the the external world that the balancer will round robin to each node. Then the stateless service uses the info from the request as key for partitioning (sharding) and thanks to the SF internal functions resolve the stateful service endpoint so that it can route the request to the proper destination, even if the stateful service changed location in the cluster because of fails, upgrades or other. So the stateless is on every node, the stateful only SF knows where is it.

I tested already your new project and it workd flawlessly, the stateless gateway intercept the incoming request, replaces the request uri with that of the stateful counter (using partition key+SF resolving functions), send the request to counter and  forward the answer back to the external client. Cool.

Now a little question about this pattern, I understand this is for a demo, but let's imagine a real world project, I could use this pattern or I could have the stateless service implementing itself the REST api and route the requests to a stateful service using a different listener, let's say a ServiceCommunicationListener. With this second pattern the con is I have to duplicate each http request from the external world into another request for the  ServiceCommunicationListener but the pros are the proxy allow me to use RPC call style, exception propagation and I wonder if the stateful primary and its replicas communicate faster between themselves since I have seen they now all expose  AspNetCommunicationListener endpoints. Would primary-replica communication be faster using ServiceCommunicationListener? Sorry  for too many questions I am very new to SF and I'm interested to understand it better.

Btw my name is Antonio (antogh = shrink of Antonio Git Hub) and I'm based in Europe 9 hrs ahead of Redmond.

Thank you and have a nice day

**Comment by weidazhao** [comment]
Hi Antonio, I haven't done any performance tests between the AspNetCommunicationListener and other listeners so I don't have an answer for this :). I know though that ASP.NET 5 team is actively working on performance tuning of the entire stack and has made very good progress so far. You can monitor https://github.com/aspnet/benchmarks (the data is a bit out-of-date now) as well as other sources like blogs, twitters to get latest progress about performance tuning.

**Comment by antogh** [comment]
Hey Weida, thank you very much for publishing this project and for the conversation, I learned a lot from both. Now I am searching new samples created from your team, I find that right after studying the theory, diving into sources written by the experts is incredibly boosting the learning curve. Not only I learn SF but sometime also other new cool features in the .NET world. Keep up with the good work, I am a big fan of your team and I am following you on various channels.
