### ISSUE TITLE
Microsoft.ServiceFabric.AspNetCore

### ISSUE THREAD

**Issue by wangkanai** [weidazhao/Hosting#21]
Would this library be publish as nuget package?

```
Microsoft.ServiceFabric.AspNetCore.Hosting
Microsoft.ServiceFabric.AspNetCore.Gateway
```

**Comment by weidazhao** [comment]
Yes, that's the plan, although we haven't finalized the release date yet. Before we have the NuGet packages, feel free to grab them as source code.

**Comment by wangkanai** [comment]
Any updates on the release date for Azure Service Fabric for ASP.NET Core on .NET Core?

**Comment by steve-torchia** [comment]
Hi @weidazhao just checking in on this to see if it's still the general idea to have nuget pkgs for Hosting and Gateway?   With the latest VS2017 there is an Asp.Net Core SF Template in preview  so it looks like things are getting closer.     The preview looks like it pulls in

`Microsoft.ServiceFabric.AspNetCore.WebListener`
`Microsoft.ServiceFabric.AspNetCore.Kestrel`
