### ISSUE TITLE
netstandard1.5

### ISSUE THREAD

**Issue by wangkanai** [weidazhao/Hosting#22]
Does Service Fabric able to run on .NET Core by using netstandard1.5?

**Comment by wangkanai** [comment]
https://github.com/weidazhao/Hosting/blob/master/Counter/project.json
is using net452 

```
  "frameworks": {
    "net452": {
      "dependencies": {
        "Microsoft.ServiceFabric": "5.0.217",
        "Microsoft.ServiceFabric.AspNetCore.Hosting": "1.0.0-*",
        "Microsoft.ServiceFabric.Services": "2.0.217"
      }
    }
  },
```

**Comment by weidazhao** [comment]
Currently the Service Fabric packages (Microsoft.ServiceFabric.*) are only available on .NET 4.5+. It doesn't run on .NET Core yet.

**Comment by grahamehorner** [comment]
@wangkanai I understand that #ServiceFabric will run netstandard and netcoreapp as an external process now; but will host them in vnext and also #ServiceFabric on #NanoServer #Linux is also coming around same timeframe?

**Comment by mani-ramaswamy** [comment]
We're actively working on both (Linux and NanoServer). While dates are still TBD, you can sign up for early Linux previews at http://aka.ms/servicefabriclinuxpreview.
