### ISSUE TITLE
Suggestion for good ASP.NET Core Development cycle ?

### ISSUE THREAD

**Issue by johnkattenhorn** [weidazhao/Hosting#27]
We are currently developing a MVC6 app which is hosted in SF and we're wondering if anyone has any suggestions on how they are managing the development experience.

I'm thinking of trying to find some conditionals that we could put around the configuration so that the site would be equally happy running inside or outside of the SF runtime.

We are currently having to deploy the site in order to see our changes which is slower than we would like.

Any tip or suggestions ?

**Comment by cwe1ss** [comment]
Hi John, we had the same problem, so we came up with our own hosting-library that also works without ServiceFabric. During development, you can just do a regular "dotnet run" to start the project.

Check out the library [C3.ServiceFabric.AspNetCore.StatelessHost](https://github.com/c3-ls/ServiceFabric-Http/wiki/Stateless-ASP.NET-Core-Host) from our [ServiceFabric-Http project](https://github.com/c3-ls/ServiceFabric-Http)

Make sure you also take a look at the samples in that project.

**Comment by johnkattenhorn** [comment]
Awesome, thanks @cwe1ss!
