### ISSUE TITLE
The EntryPoint Counter.exe is not found.

### ISSUE THREAD

**Issue by RandyWilkinson** [weidazhao/Hosting#32]
Followed the steps in the readme, then during the deployment I recieve the following message

> Register-ServiceFabricApplicationType : The EntryPoint Counter.exe is not found.
> 6>FileName: C:\SfDevCluster\Data\ImageBuilderProxy\AppType\HostingType\Counter\ServiceManifest.xml
> 6>At C:\Program Files\Microsoft SDKs\Service 
> 6>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:237 char:9
> 6>+         Register-ServiceFabricApplicationType -ApplicationPathInImageStore $appl ...
> 6>+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 6>    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Register-Servic 
> 6>   eFabricApplicationType], FabricException
> 6>    + FullyQualifiedErrorId : RegisterApplicationTypeErrorId,Microsoft.ServiceFabric.Powershell.RegisterApplicationTyp 
> 6>   e

It would appear that the executable is not being created, but I don't see any configuration around producing an exe and I don't have any local changes to the source.

**Comment by weidazhao** [comment]
Can you confirm the versions of VS, .NET Core Tools and Service Fabric SDK?

Also can you try if unloading and reloading Hosting.sfproj in VS can resolve the problem?

**Comment by RandyWilkinson** [comment]
Found the problem, I had an old version of the .net core cli installed. Removed all old .net core SDKs and CLIs, then reinstalled the Core Tools and now it works! Thank you for your help.
