### ISSUE TITLE
context.Request.Path is not set when requesting default path behind a gateway

### ISSUE THREAD

**Issue by rmja** [weidazhao/Hosting#34]
Forwarding request `/` on a gateway correctly sets the forwarded path to `/sf-someguid/`, but [this line](https://github.com/weidazhao/Hosting/blob/4cd3c78266db420b40dad2455e99ad1f20f40a4a/Microsoft.ServiceFabric.AspNetCore.Hosting/Internal/ServiceFabricServiceRegistry.cs#L100) removes the last `/` hence the request path is not set in the middleware on the backend. This causes problems with e.g. `UseDefaultFiles()` which requires the path to be defined. What is the motivation behind setting `remainingPathValue = string.Empty`?

**Comment by weidazhao** [comment]
Yup, it's a bug. I don't remember why I added that line.. I've removed it.

https://github.com/weidazhao/Hosting/commit/efc917b7e46cc055b4684091f955b33525bec41c

**Comment by rmja** [comment]
Perfect, thanks:-)
