### ISSUE TITLE
dotnet-publish.cmd not compatible with latest Service Fabric SDK (1.5.175-preview)

### ISSUE THREAD

**Issue by celer1tas** [weidazhao/Hosting#7]
When using the latest available Service Fabric SDK (1.5.175-preview), after upgrading the "Hosting" Visual Studio Project, I had to change the last line of the dotnet-publish.cmd from : 
"copy /Y %SOLUTION_FOLDER%\Hosting\ApplicationManifest.xml %PACKAGE_ROOT%\" 

to 
""copy /Y %SOLUTION_FOLDER%\Hosting\ApplicationPackageRoot\ApplicationManifest.xml %PACKAGE_ROOT%\"

**Comment by weidazhao** [comment]
Hi, I've updated the repo to target 1.5.175-preview. Thanks for the feedback. 

Please note that the current VS tools doesn't support packaging via DotNet CLI. So you might see issues with using Visual Studio now. The alternative is to use Visual Studio Code if you just want to go through source code.
